### ISSUE TITLE
Build deeplang.org based on GitHub Pages

### ISSUE THREAD

**Issue by JoeyTeng** [deeplang-org/deeplang-org.github.io#1]
Task Assigned to:
- [ ] [Joey Teng](https://github.com/orgs/deeplang-org/projects/1#column-10799364)
- [x] Create a repo and choose a theme
- [x] Update DNS records (redirect [deeplang.org](deeplang.org) and [www.deeplang.org](www.deeplang.org))
- [ ] Fill in content
  - [ ] About
  - [ ] Download
  - [ ] Documentation

**Comment by JoeyTeng** [comment]
@chinesebear Please update DNS records for this site. I have updated relevant settings in this repo.
- Create a `CNAME` record that points `www.deeplang.org` to `deeplang-org.github.io`
- Create an `A` record, pointing our apex domain `deeplang.org` to these IP addresses
```
185.199.108.153
185.199.109.153
185.199.110.153
185.199.111.153
```

Thanks :)

Reference: [https://docs.github.com/en/github/working-with-github-pages/managing-a-custom-domain-for-your-github-pages-site](https://docs.github.com/en/github/working-with-github-pages/managing-a-custom-domain-for-your-github-pages-site)

**Comment by chinesebear** [comment]
done
![image](https://user-images.githubusercontent.com/13201054/93447842-787f9000-f905-11ea-969f-9d99ed58e366.png)

**Comment by chinesebear** [comment]
> @chinesebear Please update DNS records for this site. I have updated relevant settings in this repo.
> 
> * Create a `CNAME` record that points `www.deeplang.org` to `deeplang-org.github.io`
> * Create an `A` record, pointing our apex domain `deeplang.org` to these IP addresses
> 
> ```
> 185.199.108.153
> 185.199.109.153
> 185.199.110.153
> 185.199.111.153
> ```
> 
> Thanks :)
> 
> Reference: https://docs.github.com/en/github/working-with-github-pages/managing-a-custom-domain-for-your-github-pages-site

DNS setting done!
